name: 'GoSec Enhanced Pull Requests'
description: 'Enhances the visibility for GoSec issues inside of pull requests'

inputs:
  dir:
    description: 'Directory to check with GoSec'
    required: true
    default: './...'
  failOnIssue:
    description: 'Should this action fail when GoSec finds an issue'
    required: false
    default: true

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.dir }}
    - ${{ inputs.failOnIssue }}

