on:
  pull_request:

jobs:
  run_action:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run gosec action
        uses: ./
        with:
          dir: ./exampleGoCode/...
          failOnIssue: false
